<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Posts;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param string $search
     * @return Posts[]
     */

    public function getPosts($search) {
        $qb = $this->createQueryBuilder('p');
        if($search) {
            $qb->orWhere('LOWER(p.title) like :content');
            $qb->orWhere('LOWER(p.content) like :content');
            $qb->setParameter('content', '%'.strtolower($search).'%');
        }
        $qb->addOrderBy('p.createdAt','DESC');
        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */

    public function getPostsByContent1($search) {
        $qb = $this->createQueryBuilder('p');
        if ($search) {
            $qb->where('p.content like :content');
            $qb->setParameter('content', $search.'%');
        }
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $content
     * @return array
     */

    public function getPostsByContent2($content) {
    return $this->_em->createQuery('
        SELECT p FROM AppBundle:Posts
        WHERE p.content like :content
    ')
        ->setParameter('content', $content.'%')
        ->getResult();
    }
}
