<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Posts;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return Posts[]
     */

    public function getPosts() {
        return $this->findAll();
    }

    /**
     * @return array
     */

    public function getPostsByContent1() {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.content like :content');
        $qb->setParameter('content', 'Пост%');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $content
     * @return array
     */

    public function getPostsByContent2($content) {
    return $this->_em->createQuery('
        SELECT p FROM AppBundle:Posts
        WHERE p.content like :content
    ')
        ->setParameter('content', $content.'%')
        ->getResult();
    }
}
